services:
  redis:
    image: redis:8.2
    container_name: redis_server
    restart: unless-stopped
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - /opt/redis-data:/data
    networks:
      - shiba_network

networks:
  shiba_network:
    external: true
